/**
 * 机体部件档案。name 是 GLB 内完全一致的节点名；nodeNames 可把同一模块多个网格同时选中。
 * 换模型后，请看控制台打印的节点名称，再修改这里的 name / nodeNames。
 */
export const partsData = [
  { name: 'Helmet_central_shell', nodeNames: ['Helmet central shell', 'Helmet forehead crown', 'Central helmet ridge', 'Forehead red sensor', 'Black eye visor', 'White angular mouth mask', 'Red chin', 'L luminous eye', 'R luminous eye', 'L golden main V fin', 'R golden main V fin', 'L golden lateral V fin', 'R golden lateral V fin'], displayName: '头部指挥单元', description: '集成光学传感器、复合面罩与金色 V 字天线的指挥模块，承担目标识别、姿态感知和通讯中继。', specs: { 传感器: '双目光学阵列 + 头顶天线', 装甲材质: '高强度复合陶瓷', 标识: '金色 V 字天线', 功能: '索敌 / 指挥 / 通讯' } },
  { name: 'Angular_midnight_breastplate', nodeNames: ['Angular midnight breastplate', 'Torso inner frame', 'Crimson chest crest', 'Central reactor shield', 'Chest reactor outer collar', 'Chest reactor gold core', 'L chest raised armor', 'R chest raised armor'], displayName: '胸部与主反应炉', description: '深色胸甲包覆中央反应炉，散热进气结构与红色识别装甲共同构成机体的核心视觉与能源模块。', specs: { 动力核心: '胸部高密度反应炉', 散热: '双侧进气鳍片', 防护: '分层复合装甲', 模块: '中央能量接口' } },
  { name: 'R_swept_white_shoulder', nodeNames: ['R swept white shoulder', 'R upper arm inner frame', 'R bicep armor', 'R elbow hinge', 'R forearm gauntlet', 'R hand palm', 'R thumb'], displayName: '右臂武装平台', description: '右侧肩甲、肘部关节、前臂护甲与多指机械手组成的通用操作平台，可搭载近战或射击装备。', specs: { 结构: '肩部枢轴 + 双段臂架', 关节: '外露式肘部转轴', 末端: '五指机械操控手', 用途: '主武器挂载' } },
  { name: 'L_swept_white_shoulder', nodeNames: ['L swept white shoulder', 'L upper arm inner frame', 'L bicep armor', 'L elbow hinge', 'L forearm gauntlet', 'L hand palm', 'L thumb'], displayName: '左臂防御平台', description: '与右臂采用对称的模块化架构，保留全幅关节活动范围，适合持盾、抓取与辅助近战动作。', specs: { 结构: '肩部枢轴 + 双段臂架', 关节: '外露式肘部转轴', 装甲: '白色前臂护板', 用途: '防御 / 辅助操作' } },
  { name: 'Central_groin_shield', nodeNames: ['Central groin shield', 'Pelvic frame', 'White belt', 'Red belt buckle', 'L front skirt white armor', 'R front skirt white armor', 'L hip side armor', 'R hip side armor'], displayName: '腰部与裙甲', description: '腰部柔性关节外部覆盖多片裙甲，在维持髋关节活动范围的同时为核心传动结构提供前向防护。', specs: { 结构: '多片式活动裙甲', 关节: '柔性腹部连接', 防护重点: '骨盆与髋部传动', 特征: '红色中央锁扣' } },
  { name: 'R_thigh_armor', nodeNames: ['R thigh armor', 'R knee hinge', 'R angular knee guard', 'R shin main armor', 'R ankle white cuff', 'R cobalt armored foot', 'R boot dark sole', 'L thigh armor', 'L knee hinge', 'L angular knee guard', 'L shin main armor', 'L ankle white cuff', 'L cobalt armored foot', 'L boot dark sole'], displayName: '双腿推进与行走单元', description: '大腿、膝关节、胫甲和蓝色足部构成的承力系统。多层装甲沿运动方向排布，以兼顾稳定着陆与机动能力。', specs: { 驱动: '双腿独立伺服关节', 膝部: '高扭矩铰链', 足部: '蓝色抗冲击装甲靴', 功能: '步行 / 跳跃 / 稳定着陆' } },
  { name: 'Backpack_central_reactor', nodeNames: ['Backpack central reactor', 'L upper wing binder', 'R upper wing binder', 'L long outer wing', 'R long outer wing', 'L long cobalt inset', 'R long cobalt inset', 'L backpack exhaust', 'R backpack exhaust', 'L crimson thruster surround 0', 'R crimson thruster surround 0'], displayName: '背包与翼板推进器', description: '背部大型翼板与中央反应器形成展开式推进背包。钴蓝色嵌板负责强化识别度，红色喷口用于姿态修正。', specs: { 推进: '背包矢量喷口 x2', 展开结构: '左右翼板约束器', 能源: '中央背包反应器', 功能: '高机动 / 姿态控制' } },
  { name: 'L_long_rail_sheath', nodeNames: ['L long rail sheath', 'R long rail sheath', 'L long rail silver armor', 'R long rail silver armor', 'L rail red endcap', 'R rail red endcap'], displayName: '腿侧近战武器挂架', description: '固定于两侧裙甲的长条挂架，采用银色导轨和红色端部识别件，可用于收纳近战装备或外接任务模块。', specs: { 挂载位置: '左右裙甲外侧', 导轨: '长行程银色导轨', 识别件: '红色端部护盖', 用途: '近战装备收纳' } },
  { name: 'BeamSaber', displayName: '光束军刀', description: '示例数据：请将 name 改为你的 GLB 中光束军刀节点的准确名称。', specs: { 武装: '高能粒子刃', 状态: '待匹配模型节点' } }
];
